version: '2'
services:
  app:
    extends:
      file: docker-services.yml
      service: base_app
    working_dir: /scripts
    command: node watch.js
    ports:
      - 4000:4000
  fractal:
    extends:
      file: docker-services.yml
      service: base_app
    working_dir: /web-design-standards
    command: yarn start
    stop_signal: SIGKILL
    ports:
      - 3000:3000
volumes:
  uswds-node-modules:
  uswds-docs-node-modules:
  scripts-node-modules:
  root:
  bundle:
