version: '2'
services:
  app:
    extends:
      file: docker-services.yml
      service: base_app
    working_dir: /web-design-standards
    command: npm run watch
  docs:
    extends:
      file: docker-services.yml
      service: base_app
    working_dir: /web-design-standards-docs
    command: node /scripts/watch-docs.js
  jekyll:
    extends:
      file: docker-services.yml
      service: base_app
    working_dir: /web-design-standards-docs
    # Not using `npm start` here because it runs `prestart` which
    # runs `gulp build` which we don't care about because we're already
    # running gulp separately at the same time and it could all cause
    # weird explosions.
    command: jekyll serve --drafts --future -H 0.0.0.0 --force_polling --incremental
    ports:
      - 4000:4000
  fractal:
    extends:
      file: docker-services.yml
      service: base_app
    working_dir: /web-design-standards
    command: npm start
    ports:
      - 3000:3000
volumes:
  uswds-node-modules:
  uswds-docs-node-modules:
