version: '2'
services:
  app:
    extends:
      file: docker-services.yml
      service: base_app
    working_dir: /scripts
    command: node watch.js
    environment:
      - REMOTE_CHROME_URL=http://chrome:9222
      - FRACTAL_BASE_URL=http://fractal:3000
    ports:
      - 4000:4000
    depends_on:
      - chrome
  fractal:
    extends:
      file: docker-services.yml
      service: base_app
    working_dir: /web-design-standards
    command: npm start
    stop_signal: SIGKILL
    ports:
      - 3000:3000
  chrome:
    image: yukinying/chrome-headless-browser:68.0.3440.15
    cap_add:
      - SYS_ADMIN
    stop_signal: SIGKILL
volumes:
  uswds-node-modules:
  uswds-docs-node-modules:
  scripts-node-modules:
  root:
  bundle:
