version: '2'
services:
  app:
    extends:
      file: docker-services.yml
      service: base_app
    working_dir: /web-design-standards
    command: npm start
    ports:
      - 3000:3000
volumes:
  uswds-node-modules:
  uswds-docs-node-modules:
