version: '2'
services:
  base_app:
    build: .
    volumes:
      - ./web-design-standards:/web-design-standards
      - ./web-design-standards-docs:/web-design-standards-docs
      - ./scripts:/scripts
      - uswds-node-modules:/web-design-standards/node_modules/
      - uswds-docs-node-modules:/web-design-standards-docs/node_modules/
      - scripts-node-modules:/scripts/node_modules/
      - root:/root/
      - bundle:/usr/local/bundle/
    environment:
      # Some of USWDS's development build pipelining uses `nswatch` to watch
      # for filesystem changes; this tool, in turn, uses `chokidar` to
      # do the actual watching, and its default non-polling based
      # watcher doesn't always play well with Docker setups, so we'll
      # force it to use polling by default.
      - CHOKIDAR_USEPOLLING=true
      - JEKYLL_FLAGS=--drafts --future
      - NPM_CMD=yarn
